import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,NavLink,useLocation,useNavigate} from 'react-router-dom';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,CartesianGrid,BarChart,Bar,ReferenceLine} from 'recharts';
import './style.css';
type Row=Record<string,any>;
async function api(path:string,body?:unknown){const r=await fetch('/api/v1/'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(`${r.status}: ${await r.text()}`);return r.json();}

const SCENARIOS: Record<string, string> = {
  'normal': 'Normal simulated session',
  'gradual_stress': 'Gradual stress-like change',
  'sustained_posture': 'Sustained posture deviation',
  'brief_posture': 'Brief posture deviation',
  'missing_data': 'Missing / low-quality signal',
  'high_motion': 'High-motion interference',
  'repeated_dismissal': 'Repeated prompt dismissal'
};

function App(){
 const [health,H]=useState<Row>({}),[sessions,S]=useState<Row[]>([]),[selected,SEL]=useState(''),[events,E]=useState<Row[]>([]),[prompts,P]=useState<Row[]>([]),[models,M]=useState<Row[]>([]),[runs,R]=useState<Row[]>([]),[jobs,J]=useState<Row[]>([]),[privacy,V]=useState<Row[]>([]),[projections,PROJ]=useState<Row[]>([]),[error,ERR]=useState(''),[scenario,SC]=useState('normal'),[speed,SP]=useState(20),[explanation,X]=useState<Row|null>(null),[explainModel,XM]=useState('neural');
 const [mode, setMode] = useState(()=>localStorage.getItem('nexora-view') || 'research');
 const navigate=useNavigate();
 const routerLocation=useLocation();const pageRaw=decodeURIComponent(routerLocation.pathname.slice(1));const page=pageRaw?pageRaw:mode==='research'?'Overview':'Home';
 
 const refresh=async()=>{try{const [h,s,p,m,r,v,proj]=await Promise.all([api('health'),api('sessions'),api('interventions'),api('metrics'),api('experiments'),api('privacy'),api('privacy/projection')]);H(h);S(s);P(p);M(m);R(r);V(v);PROJ(proj);if(h.coordinator==='available'){try{J(await api('experiment-jobs'))}catch{J([])}}else J([]);ERR('');if(!selected&&s.length)SEL(s[0].id);}catch(e){ERR(String(e));H({status:'disconnected'});}};
 useEffect(()=>{refresh();const timer=setInterval(refresh,2000);return()=>clearInterval(timer)},[selected]);
 useEffect(()=>{E([]);X(null);if(!selected)return;let active=true,cursor=0,socket:WebSocket|undefined,retry:number|undefined;const append=(rows:Row[])=>{if(active&&rows.length){cursor=rows[rows.length-1].sequence;E(old=>{const ids=new Set(old.map(item=>item.event_id));return [...old,...rows.filter(item=>!ids.has(item.event_id))].slice(-1500)})}};const connect=async()=>{try{append(await api(`sessions/${selected}/events?after=${cursor}&limit=1000`));const scheme=window.location.protocol==='https:'?'wss':'ws';socket=new WebSocket(`${scheme}://${window.location.host}/api/v1/sessions/${selected}/stream?after=${cursor}`);socket.onmessage=e=>append([JSON.parse(e.data)]);socket.onclose=()=>{if(active)retry=window.setTimeout(connect,750)};socket.onerror=()=>socket?.close();}catch(e){if(active){ERR(String(e));retry=window.setTimeout(connect,750)}}};connect();return()=>{active=false;if(retry)clearTimeout(retry);socket?.close()}},[selected]);
 
 const researchPages = ['Overview', 'Live session', 'Interventions', 'AI insights', 'Federated & privacy lab', 'Evidence', 'Settings'];
 const userPages = ['Home', 'Guidance', 'History', 'About', 'Settings'];
 const activePages = mode === 'research' ? researchPages : userPages;
 const setAppMode=(next:string)=>{setMode(next);localStorage.setItem('nexora-view',next);navigate(next==='research'?'/Overview':'/Home');};

 const act=async(fn:()=>Promise<unknown>)=>{try{await fn();await refresh()}catch(e){ERR(String(e))}};
 const exportEvidence=()=>{window.location.href='/api/v1/evidence/export';};
 const start=()=>act(async()=>{const s=await api('sessions',{scenario,speed,seed:42});SEL(s.id);await api(`sessions/${s.id}/start`,{})});
 
 const session=sessions.find(s=>s.id===selected);
 const obs=events.filter(e=>e.event_type==='observation').map(e=>({...e.payload,...e.payload.signals}));
 const latest=obs.at(-1);
 const pred=events.filter(e=>e.event_type==='prediction').at(-1)?.payload;
 const activePrompts=prompts.filter(p=>(p.status==='offered'||p.status==='accepted')&&(!selected||p.session_id===selected));
 const activeModel = models.find(m => m.lifecycle_state === 'active') || models[0];

 const renderChart=(title:string, dataKey:string, unit:string, stroke:string)=>{
   return <div className="card"><div className="cardtitle"><h2>{title}</h2><span>Synthetic · {unit}</span></div><ResponsiveContainer width="100%" height={150}><LineChart data={obs.filter((_,i)=>i%4===0)}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="event_time_s" unit="s"/><YAxis/><Tooltip/><Line type="monotone" dataKey={dataKey} stroke={stroke} dot={false} isAnimationActive={false} connectNulls={false}/></LineChart></ResponsiveContainer></div>;
 };

 return <div className="shell"><aside><div className="brand"><b>◈ NEXORA</b><small>{mode === 'research' ? 'RESEARCH CONSOLE' : 'PARTICIPANT APP'}</small></div>
 <div className="mode-toggle" style={{padding: '0 1rem', marginBottom: '1rem'}}>
    <label style={{display: 'flex', alignItems: 'center', gap: '0.5rem', color: '#fff', fontSize: '0.875rem'}}>
      <input aria-label="Research Mode" type="checkbox" checked={mode==='research'} onChange={(e) => setAppMode(e.target.checked ? 'research' : 'user')} />
      Research Mode
    </label>
 </div>
 <nav>{activePages.map((p,i)=><NavLink key={p} to={'/'+p}><span>{['▦','⌁','◎','◇','⬡','▤','⚙'][i % 7]}</span><span>{p}</span></NavLink>)}</nav><div className="asidebottom"><span className="dot"/> Local workspace<small>Software-in-the-loop prototype</small></div></aside><main><header><span>Workspace / <b>{page}</b></span><div className="badges"><span className="badge">Synthetic</span><span className="badge">{health.client_id||'client-a'}</span><span className="badge">Edge {health.status||'Connecting…'}</span><span className="badge">Coordinator {health.coordinator||'unknown'}</span></div></header><section><div className="title"><div><p className="eyebrow">NEXORA / {mode === 'research' ? 'RESEARCH WORKSPACE' : 'PARTICIPANT DASHBOARD'}</p><h1>{page}</h1><p>{mode==='research'?'Inspect signals, model behaviour and traceable software decisions.':'Follow the local simulation and choose whether to use an optional suggestion.'}</p></div><span className="badge">{health.transport||'Connecting…'}</span></div>{error&&<div role="alert" className="error">{error}</div>}
 
 {page==='Overview'&&mode==='research'&&<><div className="card controls"><label>Scenario<select value={scenario} onChange={e=>SC(e.target.value)}>{Object.entries(SCENARIOS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Replay speed<select value={speed} onChange={e=>SP(+e.target.value)}>{[1,5,20].map(x=><option key={x} value={x}>{x}×</option>)}</select></label><button onClick={start}>Start synthetic session</button><button className="secondary" disabled={!session||session.status==='stopped'} onClick={()=>act(()=>api(`sessions/${selected}/${session?.status==='running'?'pause':'start'}`,{}))}>{session?.status==='running'?'Pause':'Resume'}</button><button className="secondary" disabled={!session||session.status==='stopped'} onClick={()=>act(()=>api(`sessions/${selected}/stop`,{}))}>Stop</button></div>
 <div className="card"><h2>Architecture Pipeline</h2>
 <div style={{display:'flex', gap:'1rem', overflowX:'auto', padding:'1rem 0'}}>
   <div className="pipeline-node"><b>Source</b><br/>{latest?'Synthetic':'WESAD unavailable'}</div>
   <div className="pipeline-node"><b>Quality</b><br/>{pred?.abstained?'missing/high-motion':'good'}</div>
   <div className="pipeline-node"><b>Features</b><br/>12 features</div>
   <div className="pipeline-node"><b>Model</b><br/>{activeModel ? activeModel.model_hash?.slice(0,8) : 'None'}</div>
   <div className="pipeline-node"><b>Policy</b><br/>Threshold {activeModel?.threshold != null ? activeModel.threshold : "Unavailable"}</div>
   <div className="pipeline-node"><b>Intervention</b><br/>{activePrompts.length?'Offered':'None'}</div>
   <div className="pipeline-node"><b>Feedback</b><br/>{events.filter(e=>e.event_type==='feedback').at(-1)?.payload.action || 'None'}</div>
 </div>
 </div>
 <div className="card"><h2>Session Summary</h2><p>Active session ID: {selected || 'None'}</p><p>Status: {session?.status || 'Unknown'}</p><p>Go to Live session to see real-time signals.</p></div></>}
 
 {page==='Live session'&&mode==='research'&&<><div className="stats">{[['EDA',latest?.eda_us,'µS'],['Skin temperature',latest?.skin_temperature_c,'°C'],['Posture',latest?.posture_angle_deg,'°'],['Heart rate',latest?.heart_rate_bpm,'bpm']].map(([name,value,unit])=><div className="card" key={name}><small>{name}</small><strong>{value==null?'Unavailable':Number(value).toFixed(2)} <em>{value==null?'':unit}</em></strong><span>Synthetic source</span></div>)}</div>
 <div className="twocol">
   {renderChart('Electrodermal activity', 'eda_us', 'µS', '#087f83')}
   {renderChart('Posture', 'posture_angle_deg', '°', '#d35400')}
 </div>
 <div className="twocol"><div className="card"><h2>Model state</h2><p>{!pred?'Waiting for a complete 30-second window':pred.abstained?'Abstained: '+pred.reason:`Stress model score: ${(pred.probabilities[1]*100).toFixed(1)}%`}</p><p className="muted">Scores are uncalibrated model outputs. No diagnosis.</p><p>Active Hash: {activeModel?.model_hash?.slice(0,8) || 'unknown'}</p><p>Threshold: {activeModel?.threshold != null ? activeModel.threshold : <em>Unavailable</em>}</p><span className="badge">{session?.status||'No active session'} · {session?.speed||speed}×</span></div><div className="card"><h2>Recent decisions</h2>{events.filter(e=>e.event_type==='decision').slice(-4).reverse().map(e=><div className="row" key={e.event_id}><b>{e.payload.result}</b><span>{e.payload.reason_codes.join(', ')}</span></div>)}</div></div></>}
 
 {page==='Home'&&mode==='user'&&<><div className="participant-hero"><span className="eyebrow">Synthetic demonstration data</span><h2>{session?.status==='running'?'Monitoring simulation is active':session?.status==='paused'?'Monitoring simulation is paused':'Ready to start a monitoring simulation'}</h2><p>{pred?.abstained?'Signal quality is insufficient.':activePrompts.length?'NEXORA has a small suggestion.':'This demonstration watches simulated signals and offers guidance.'}</p><span className="badge">Runs locally on this laptop</span></div><div className="stats participant-signals">{[['Signal 1',latest?.eda_us,'available'],['Signal 2',latest?.skin_temperature_c,'available'],['Signal 3',latest?.posture_angle_deg,'available']].map(([name,value,state])=><div className="card" key={String(name)}><small>{name}</small><strong>{value==null?'Unavailable':'Active'}</strong><span>{state==='available'?'Synthetic source':'Not supplied by this demo'}</span></div>)}</div><div className="card controls"><button onClick={start}>Start Session</button><button className="secondary" disabled={!session||session.status==='stopped'} onClick={()=>act(()=>api(`sessions/${selected}/${session?.status==='running'?'pause':'start'}`,{}))}>{session?.status==='running'?'Pause':'Resume'}</button><button className="secondary" disabled={!session||session.status==='stopped'} onClick={()=>act(()=>api(`sessions/${selected}/stop`,{}))}>End session</button></div></>}

 {page==='Guidance'&&mode==='user'&&<div className="card guidance"><h2>Current guidance</h2>{!activePrompts.length&&<p>No action is needed right now. Start a session to see the simulated workflow.</p>}{activePrompts.map(p=><article key={p.id}><span className="badge">Optional suggestion</span><h3>{p.text}</h3><p>Take a moment to reset. You remain in control.</p>{(p.status==='offered'?['accept','dismiss']:p.status==='accepted'?['complete','cancel']:[]).map(action=><button key={action} onClick={()=>act(()=>api(`interventions/${p.id}/feedback`,{feedback_id:crypto.randomUUID(),action}))}>{action==='complete'?'Done':action==='accept'?'Start':action}</button>)}</article>)}</div>}
 
 {page==='History'&&mode==='user'&&<div className="card"><h2>Session history</h2><p className="muted">Sessions are retained in local SQLite storage on this device.</p>{!sessions.length&&<p>No sessions yet. Start a session from the Home page.</p>}{sessions.map(s=><article key={s.id} style={{marginBottom:'1rem',padding:'1rem',background:'var(--surface)',borderRadius:'0.5rem',border:s.id===selected?'1px solid var(--accent)':'1px solid #333',cursor:'pointer'}} onClick={()=>SEL(s.id)}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><span className="badge">{SCENARIOS[s.scenario]||s.scenario}</span><span className="badge">{s.status}</span></div><h3 style={{margin:'0.5rem 0'}}>{s.id.slice(0,8)}…</h3><div style={{display:'flex',gap:'1rem',fontSize:'0.8rem',color:'#aaa'}}><span>Created: {new Date(s.created_at).toLocaleString()}</span>{s.status==='stopped'&&<span>Duration: {s.started_at&&s.stopped_at?((new Date(s.stopped_at).getTime()-new Date(s.started_at).getTime())/1000).toFixed(0)+'s':'—'}</span>}</div><p style={{margin:'0.5rem 0 0',color:'#888',fontSize:'0.8rem'}}>{events.filter(e=>e.session_id===s.id&&e.event_type==='prediction').length} predictions · {events.filter(e=>e.session_id===s.id&&e.event_type==='feedback').length} feedback events</p></article>)}</div>}
 
 {page==='About'&&mode==='user'&&<div className="card"><h2>About this prototype</h2><p>Local prototype scope only. Not a medical device. Uses synthetic inputs. No clinical validation or hardware claims.</p></div>}
 
 {page==='Interventions'&&mode==='research'&&<div className="card"><h2>Prompts & feedback</h2>{!prompts.length&&<p>No prompts yet. Start the sustained posture scenario to exercise the context policy.</p>}{prompts.map(p=><article key={p.id}><span className="badge">{p.source} · {p.status}</span><h3>{p.text}</h3><p>Physical output not connected.</p>{(p.status==='offered'?['accept','dismiss']:p.status==='accepted'?['complete','cancel']:[]).map(action=><button key={action} onClick={()=>act(()=>api(`interventions/${p.id}/feedback`,{feedback_id:crypto.randomUUID(),action}))}>{action}</button>)}</article>)}</div>}
 
 {page==='AI insights'&&mode==='research'&&<><div className="twocol">{models.map(m=><div className="card" key={m.model_hash}><span className="badge">{m.source} · {m.lifecycle_state||'candidate'}</span><h2>{m.model_id==='baseline'?'Random forest':'Neural network'}</h2><strong className="metric">{(100*(m.validation_score || m.metrics?.balanced_accuracy || 0)).toFixed(1)}%</strong><p>Validation Balanced accuracy</p><p>Test Balanced Acc: {(100*(m.test_balanced_accuracy || m.metrics?.balanced_accuracy || 0)).toFixed(1)}% · Macro-F1: {(m.test_macro_f1 || m.metrics?.macro_f1 || 0).toFixed(3)}</p><p>Architecture: {m.architecture_id || 'Unavailable'}</p><p>Hash: {m.model_hash}</p><div><h4>Confusion Matrix</h4><table style={{width:'100%', textAlign:'center'}}><thead><tr><th>Actual \ Pred</th><th>Baseline</th><th>Stress-like</th></tr></thead><tbody><tr><td>Baseline</td><td>{m.metrics?.confusion_matrix?.[0]?.[0]}</td><td>{m.metrics?.confusion_matrix?.[0]?.[1]}</td></tr><tr><td>Stress-like</td><td>{m.metrics?.confusion_matrix?.[1]?.[0]}</td><td>{m.metrics?.confusion_matrix?.[1]?.[1]}</td></tr></tbody></table></div><div className="alert-box" style={{marginTop:'1rem', padding:'1rem', background:'#ffeeba', color:'#856404'}}><strong>Synthetic simulator result only</strong> — not real-world stress-detection accuracy.</div></div>)}</div><div className="card"><h2>Per-prediction attribution</h2><label>Model<select value={explainModel} onChange={e=>{XM(e.target.value);X(null)}}><option value="neural">Neural network</option><option value="baseline">Random forest</option></select></label><button disabled={!pred?.prediction_id} onClick={()=>act(async()=>X(await api(`explanations/${pred.prediction_id}?model=${explainModel}`)))}>Explain latest prediction</button>{explanation&&<><p>{explanation.method} · {explanation.output_space} · class {explanation.class}</p>
 <ResponsiveContainer width="100%" height={300}>
   <BarChart data={explanation.values.map((v:number,i:number)=>({name: explanation.feature_names[i], value: v}))} layout="vertical" margin={{left: 50}}>
     <CartesianGrid strokeDasharray="3 3"/>
     <XAxis type="number"/>
     <YAxis dataKey="name" type="category" width={100}/>
     <Tooltip/>
     <ReferenceLine x={0} stroke="#000" />
     <Bar dataKey="value" fill="#8884d8" />
   </BarChart>
 </ResponsiveContainer>
 <p>Completeness delta: {(explanation.convergence_delta??explanation.completeness_delta).toFixed(7)}</p><p className="muted">Attribution describes model behaviour, not causality or clinical effect.</p></>}</div></>}
 
 {page==='Federated & privacy lab'&&mode==='research'&&<><div className="card controls"><button disabled={health.coordinator!=='available'||jobs.some(j=>['queued','training'].includes(j.status))} onClick={()=>act(()=>api('experiment-jobs',{mode:'federated',rounds:1}))}>Run 1-round FedAvg</button><button disabled={health.coordinator!=='available'||jobs.some(j=>['queued','training'].includes(j.status))} onClick={()=>act(()=>api('experiment-jobs',{mode:'federated',rounds:3}))}>Run 3-round FedAvg</button><button disabled={health.coordinator!=='available'||jobs.some(j=>['queued','training'].includes(j.status))} onClick={()=>act(()=>api('experiment-jobs',{mode:'private-federated',rounds:1}))}>Run private FedAvg</button><span className="badge">Coordinator {health.coordinator}</span></div>
 <div className="card"><h2>Client Topology</h2><p className="muted">Three isolated processes on the same host. Secure aggregation is NOT implemented.</p><div style={{display:'flex',gap:'1rem',flexWrap:'wrap',margin:'1rem 0'}}>{['client-a','client-b','client-c'].map(cid=>{const priv=privacy.find(v=>v.client_id===cid);return(<div key={cid} style={{flex:'1 1 150px',padding:'1rem',background:'var(--surface)',borderRadius:'0.5rem',border:'1px solid #333',textAlign:'center'}}><b style={{color:'var(--accent)'}}>{cid}</b><br/><small>Port {cid==='client-a'?8080:cid==='client-b'?8082:8083}</small><br/>{priv?<><small>ε {priv.epsilon.toFixed(2)}</small><br/><small>{priv.steps} DP steps</small></>:<small style={{color:'#888'}}>No DP data yet</small>}</div>)})}</div><div style={{textAlign:'center',padding:'0.5rem',color:'#555'}}>↕ HTTP (loopback)</div><div style={{padding:'1rem',background:'var(--surface)',borderRadius:'0.5rem',border:'1px solid var(--accent)',textAlign:'center'}}><b>Coordinator</b><br/><small>Port 8081 · FedAvg aggregation</small></div><p className="muted" style={{marginTop:'1rem',fontSize:'0.8rem'}}>Same-host: YES · Secure aggregation: NO · Opacus: ENABLED · Secure RNG: NO</p></div>
 {jobs.length>0&&<div className="card"><h2>Experiment jobs</h2>{jobs.slice(0,5).map(j=><div className="row" key={j.job_id}><span>{j.mode} · {j.rounds} round · {j.status}</span><span>{j.job_id.slice(0,8)} {['queued','training'].includes(j.status)&&<button onClick={()=>act(()=>api(`experiment-jobs/${j.job_id}/cancel`,{}))}>Cancel</button>}</span></div>)}</div>}<div className="stats">{privacy.map(v=><div className="card" key={v.client_id}><small>{v.client_id} · same laptop</small><strong>ε {v.epsilon.toFixed(3)}</strong><span>δ {v.delta} · {v.steps} steps</span><p className="muted">{v.accountant} · {v.randomness_mode.replaceAll('_',' ')}</p></div>)}</div><div className="card"><h2>Measured experiment runs</h2>{!runs.length&&<p>No completed distributed run.</p>}{runs.map(r=><article key={r.run_id}><span className="badge">{r.mode} · {r.source} · {r.status}</span><h3>{r.rounds.length} round{r.rounds.length===1?'':'s'} · val. score {(r.validation_score*100 || 0).toFixed(1)}%</h3><p>Run {r.run_id}</p><p>Candidate Hash: {r.model_hash}</p>
 <button onClick={()=>act(()=>api(`models/${r.run_id}/activate`,{round:r.rounds.length}))}>Activate Candidate</button><button className="secondary" style={{marginLeft:'0.5rem'}} onClick={()=>act(()=>api(`models/rollback`,{}))}>Rollback to Previous</button>
 {r.rounds.map((round:Row)=><div className="row" key={round.round}><span>Round {round.round}: {round.clients.map((c:Row)=>`${c.client_id} ${c.records} records`).join(' · ')}</span><b>Base: {round.base_hash?.slice(0,8)}... Update: {round.model_hash?.slice(0,8)}...</b></div>)}</article>)}</div></>}
 
 {page==='Evidence'&&mode==='research'&&<div className="card"><h2>Evidence package</h2><p>Signals and measured model results use generated synthetic data. WESAD: NOT RUN. Hardware: NOT BUILT. Clinical validation: NOT PERFORMED.</p><div style={{background:'var(--surface)',borderRadius:'0.5rem',padding:'1rem',marginBottom:'1rem'}}><p><strong>Active model:</strong> {activeModel?activeModel.model_hash?.slice(0,8)||'None':'No active model'}</p><p><strong>Architecture:</strong> {activeModel?.architecture_id||'Unavailable'}</p><p><strong>Threshold:</strong> {activeModel?.threshold!=null?activeModel.threshold:'Unavailable'}</p><p><strong>Lifecycle:</strong> {activeModel?.lifecycle_state||'Unavailable'}</p><p><strong>Source:</strong> Synthetic dataset (seeded, artificial)</p><p><strong>Verification:</strong> Hash-indexed; see export-manifest.json inside ZIP</p></div><button onClick={exportEvidence} id="download-evidence-zip">Download ZIP Evidence</button></div>}
 
 {page==='Settings'&&<><div className="card"><h2>Settings</h2><p className="muted">These settings apply to this browser session only.</p><label style={{display:'block',marginBottom:'1rem'}}>Replay speed (applies to next session start)<select value={speed} onChange={e=>SP(+e.target.value)}><option value={1}>1× (slow)</option><option value={5}>5× (medium)</option><option value={20}>20× (fast)</option></select></label><label style={{display:'flex',alignItems:'center',gap:'0.5rem',marginBottom:'1rem'}}><input type="checkbox" id="reduced-motion" onChange={e=>{if(e.target.checked){document.body.classList.add('reduce-motion')}else{document.body.classList.remove('reduce-motion')}}} aria-label="Reduce animations"/><span>Reduce animations (accessibility)</span></label><div className="muted" style={{fontSize:'0.8rem',marginTop:'1rem'}}><p>Active model hash: {activeModel?.model_hash?.slice(0,8)||'None'}</p><p>Threshold: {activeModel?.threshold!=null?activeModel.threshold:'Unavailable'}</p><p>Architecture: {activeModel?.architecture_id||'Unavailable'}</p></div></div></>}
 </section><footer>Research prototype · Recorded/simulated inputs · No live health measurements.</footer></main></div>
}
createRoot(document.getElementById('root')!).render(<BrowserRouter><App/></BrowserRouter>);
