import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,NavLink,useLocation} from 'react-router-dom';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,CartesianGrid} from 'recharts';
import './style.css';
type Row=Record<string,any>;
async function api(path:string,body?:unknown){const r=await fetch('/api/v1/'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(`${r.status}: ${await r.text()}`);return r.json();}
const pages=['Overview','Live session','Interventions','AI insights','Federated & privacy lab','Evidence','Settings'];
function App(){
 const [health,H]=useState<Row>({}),[sessions,S]=useState<Row[]>([]),[selected,SEL]=useState(''),[events,E]=useState<Row[]>([]),[prompts,P]=useState<Row[]>([]),[models,M]=useState<Row[]>([]),[runs,R]=useState<Row[]>([]),[jobs,J]=useState<Row[]>([]),[privacy,V]=useState<Row[]>([]),[error,ERR]=useState(''),[scenario,SC]=useState('normal'),[speed,SP]=useState(20),[explanation,X]=useState<Row|null>(null),[explainModel,XM]=useState('neural');
 const routerLocation=useLocation();const page=decodeURIComponent(routerLocation.pathname.slice(1))||'Overview';
 const refresh=async()=>{try{const [h,s,p,m,r,v]=await Promise.all([api('health'),api('sessions'),api('interventions'),api('metrics'),api('experiments'),api('privacy')]);H(h);S(s);P(p);M(m);R(r);V(v);if(h.coordinator==='available'){try{J(await api('experiment-jobs'))}catch{J([])}}else J([]);ERR('');if(!selected&&s.length)SEL(s[0].id);}catch(e){ERR(String(e));H({status:'disconnected'});}};
 useEffect(()=>{refresh();const timer=setInterval(refresh,2000);return()=>clearInterval(timer)},[selected]);
 useEffect(()=>{E([]);X(null);if(!selected)return;let active=true,cursor=0,socket:WebSocket|undefined,retry:number|undefined;const append=(rows:Row[])=>{if(active&&rows.length){cursor=rows[rows.length-1].sequence;E(old=>{const ids=new Set(old.map(item=>item.event_id));return [...old,...rows.filter(item=>!ids.has(item.event_id))].slice(-1500)})}};const connect=async()=>{try{append(await api(`sessions/${selected}/events?after=${cursor}&limit=1000`));const scheme=window.location.protocol==='https:'?'wss':'ws';socket=new WebSocket(`${scheme}://${window.location.host}/api/v1/sessions/${selected}/stream?after=${cursor}`);socket.onmessage=e=>append([JSON.parse(e.data)]);socket.onclose=()=>{if(active)retry=window.setTimeout(connect,750)};socket.onerror=()=>socket?.close();}catch(e){if(active){ERR(String(e));retry=window.setTimeout(connect,750)}}};connect();return()=>{active=false;if(retry)clearTimeout(retry);socket?.close()}},[selected]);
 const [mode, setMode] = useState('research');
 const researchPages = ['Overview', 'Live session', 'Interventions', 'AI insights', 'Federated & privacy lab', 'Evidence', 'Settings'];
 const userPages = ['Overview', 'Live session', 'Settings'];
 const activePages = mode === 'research' ? researchPages : userPages;

 const act=async(fn:()=>Promise<unknown>)=>{try{await fn();await refresh()}catch(e){ERR(String(e))}};
 const start=()=>act(async()=>{const s=await api('sessions',{scenario,speed,seed:42});SEL(s.id);await api(`sessions/${s.id}/start`,{})});
 const session=sessions.find(s=>s.id===selected),obs=events.filter(e=>e.event_type==='observation').map(e=>({...e.payload,...e.payload.signals})),latest=obs.at(-1),pred=events.filter(e=>e.event_type==='prediction').at(-1)?.payload;
 const chart=<div className="card"><div className="cardtitle"><h2>Electrodermal activity</h2><span>Synthetic · µS · event time</span></div><ResponsiveContainer width="100%" height={260}><LineChart data={obs.filter((_,i)=>i%4===0)}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="event_time_s" unit="s"/><YAxis/><Tooltip/><Line type="monotone" dataKey="eda_us" stroke="#087f83" dot={false} isAnimationActive={false} connectNulls={false}/></LineChart></ResponsiveContainer></div>;
 return <div className="shell"><aside><div className="brand"><b>◈ NEXORA</b><small>{mode === 'research' ? 'RESEARCH CONSOLE' : 'PARTICIPANT APP'}</small></div>
 <div className="mode-toggle" style={{padding: '0 1rem', marginBottom: '1rem'}}>
    <label style={{display: 'flex', alignItems: 'center', gap: '0.5rem', color: '#fff', fontSize: '0.875rem'}}>
      <input type="checkbox" checked={mode==='research'} onChange={(e) => {setMode(e.target.checked ? 'research' : 'user'); window.location.hash = '/Overview';}} />
      Research Mode
    </label>
 </div>
 <nav>{activePages.map((p,i)=><NavLink key={p} to={'/'+p}><span>{['▦','⌁','◎','◇','⬡','▤','⚙'][i]}</span><span>{p}</span></NavLink>)}</nav><div className="asidebottom"><span className="dot"/> Local workspace<small>Software-in-the-loop prototype</small></div></aside><main><header><span>Workspace / <b>{page}</b></span><div className="badges"><span className="badge">Synthetic</span><span className="badge">{health.client_id||'client-a'}</span><span className="badge">Edge {health.status||'Connecting…'}</span><span className="badge">Coordinator {health.coordinator||'unknown'}</span></div></header><section><div className="title"><div><p className="eyebrow">NEXORA / {mode === 'research' ? 'RESEARCH WORKSPACE' : 'PARTICIPANT DASHBOARD'}</p><h1>{page}</h1><p>Inspect signals, model behaviour and traceable software decisions.</p></div><span className="badge">{health.transport||'Connecting…'}</span></div>{error&&<div role="alert" className="error">{error}</div>}
 {page==='Overview'&&<><div className="card controls"><label>Scenario<select value={scenario} onChange={e=>SC(e.target.value)}>{['normal','gradual_stress','sustained_posture','brief_posture','missing_data','high_motion','repeated_dismissal'].map(x=><option key={x}>{x}</option>)}</select></label><label>Replay speed<select value={speed} onChange={e=>SP(+e.target.value)}>{[1,5,20].map(x=><option key={x} value={x}>{x}×</option>)}</select></label><button onClick={start}>Start synthetic session</button><button className="secondary" disabled={!session||session.status==='stopped'} onClick={()=>act(()=>api(`sessions/${selected}/${session?.status==='running'?'pause':'start'}`,{}))}>{session?.status==='running'?'Pause':'Resume'}</button><button className="secondary" disabled={!session||session.status==='stopped'} onClick={()=>act(()=>api(`sessions/${selected}/stop`,{}))}>Stop</button></div>
 <div className="card"><h2>Session Summary</h2><p>Active session ID: {selected || 'None'}</p><p>Status: {session?.status || 'Unknown'}</p><p>You are viewing the Overview page. Go to Live session to see real-time signals.</p></div></>}
 {page==='Live session'&&<><div className="stats">{[['EDA',latest?.eda_us,'µS'],['Skin temperature',latest?.skin_temperature_c,'°C'],['Posture',latest?.posture_angle_deg,'°'],['Heart rate',latest?.heart_rate_bpm,'bpm']].map(([name,value,unit])=><div className="card" key={name}><small>{name}</small><strong>{value==null?'Unavailable':Number(value).toFixed(2)} <em>{value==null?'':unit}</em></strong><span>Synthetic source</span></div>)}</div>{chart}<div className="twocol"><div className="card"><h2>Model state</h2><p>{!pred?'Waiting for a complete 30-second window':pred.abstained?'Abstained: '+pred.reason:`Stress model score: ${(pred.probabilities[1]*100).toFixed(1)}%`}</p><p className="muted">Scores are uncalibrated model outputs. No diagnosis.</p><span className="badge">{session?.status||'No active session'} · {session?.speed||speed}×</span></div><div className="card"><h2>Recent decisions</h2>{events.filter(e=>e.event_type==='decision').slice(-4).reverse().map(e=><div className="row" key={e.event_id}><b>{e.payload.result}</b><span>{e.payload.reason_codes.join(', ')}</span></div>)}</div></div></>}
 {page==='Interventions'&&mode==='research'&&<div className="card"><h2>Prompts & feedback</h2>{!prompts.length&&<p>No prompts yet. Start the sustained posture scenario to exercise the context policy.</p>}{prompts.map(p=><article key={p.id}><span className="badge">{p.source} · {p.status}</span><h3>{p.text}</h3><p>Physical output not connected.</p>{(p.status==='offered'?['accept','dismiss']:p.status==='accepted'?['complete','cancel']:[]).map(action=><button key={action} onClick={()=>act(()=>api(`interventions/${p.id}/feedback`,{feedback_id:crypto.randomUUID(),action}))}>{action}</button>)}</article>)}</div>}
 {page==='AI insights'&&mode==='research'&&<><div className="twocol">{models.map(m=><div className="card" key={m.model_id}><span className="badge">{m.source} · held-out subjects</span><h2>{m.model_id==='baseline'?'Random forest':'Neural network'}</h2><strong className="metric">{(100*m.metrics.balanced_accuracy).toFixed(1)}%</strong><p>Balanced accuracy · macro-F1 {m.metrics.macro_f1.toFixed(3)}</p><p>{m.metrics.windows} windows · {m.splits.test.length} test subjects</p><pre>{JSON.stringify(m.metrics.confusion_matrix)}</pre><p className="muted">Measured fit to this artificial generator only.</p></div>)}</div><div className="card"><h2>Per-prediction attribution</h2><label>Model<select value={explainModel} onChange={e=>{XM(e.target.value);X(null)}}><option value="neural">Neural network</option><option value="baseline">Random forest</option></select></label><button disabled={!pred?.prediction_id} onClick={()=>act(async()=>X(await api(`explanations/${pred.prediction_id}?model=${explainModel}`)))}>Explain latest prediction</button>{explanation&&<><p>{explanation.method} · {explanation.output_space} · class {explanation.class}</p>{explanation.values.map((v:number,i:number)=><div className="row" key={i}><span>{explanation.feature_names[i]}</span><b>{v.toFixed(5)}</b></div>)}<p>Completeness delta: {(explanation.convergence_delta??explanation.completeness_delta).toFixed(7)}</p><p className="muted">Attribution describes model behaviour, not causality or clinical effect.</p></>}</div></>}
 {page==='Federated & privacy lab'&&mode==='research'&&<><div className="card controls"><button disabled={health.coordinator!=='available'||jobs.some(j=>['queued','training'].includes(j.status))} onClick={()=>act(()=>api('experiment-jobs',{mode:'federated',rounds:1}))}>Run 1-round FedAvg</button><button disabled={health.coordinator!=='available'||jobs.some(j=>['queued','training'].includes(j.status))} onClick={()=>act(()=>api('experiment-jobs',{mode:'private-federated',rounds:1}))}>Run private FedAvg</button><span className="badge">Coordinator {health.coordinator}</span></div>{jobs.length>0&&<div className="card"><h2>Experiment jobs</h2>{jobs.slice(0,5).map(j=><div className="row" key={j.job_id}><span>{j.mode} · {j.rounds} round · {j.status}</span><span>{j.job_id.slice(0,8)} {['queued','training'].includes(j.status)&&<button onClick={()=>act(()=>api(`experiment-jobs/${j.job_id}/cancel`,{}))}>Cancel</button>}</span></div>)}</div>}<div className="stats">{privacy.map(v=><div className="card" key={v.client_id}><small>{v.client_id} · same laptop</small><strong>ε {v.epsilon.toFixed(3)}</strong><span>δ {v.delta} · {v.steps} steps</span><p className="muted">{v.accountant} · {v.randomness_mode.replaceAll('_',' ')}</p></div>)}</div><div className="card"><h2>Measured experiment runs</h2>{!runs.length&&<p>No completed distributed run.</p>}{runs.map(r=><article key={r.run_id}><span className="badge">{r.mode} · {r.source} · {r.status}</span><h3>{r.rounds.length} round{r.rounds.length===1?'':'s'} · balanced accuracy {(r.metrics.balanced_accuracy*100).toFixed(1)}%</h3><p>Run {r.run_id}</p>{r.rounds.map((round:Row)=><div className="row" key={round.round}><span>Round {round.round}: {round.clients.map((c:Row)=>`${c.client_id} ${c.records} records`).join(' · ')}</span><b>{round.model_hash.slice(0,12)}…</b></div>)}</article>)}</div><div className="card"><h2>Privacy scope</h2><p>Example-level protection for non-overlapping 30-second synthetic windows. The maximum client epsilon is shown; values are not summed across disjoint clients.</p><p>Secure randomness is unavailable in this run. The Opacus experimental non-cryptographic mode is not deployment-grade.</p></div></>}
 {page==='Evidence'&&mode==='research'&&<div className="card"><h2>Build evidence console</h2><p>Signals and measured model results use generated synthetic data. The WESAD offline adapter is tested, but no real WESAD files have been imported or evaluated.</p><p>Physical sensors, haptics, cloud hosting and clinical efficacy are not demonstrated.</p>
 <h3>Claim Matrix</h3>
 <ul><li>Data provenance: Synthetic deterministic generator with WESAD support</li><li>Model version: Neural network (safetensors) + Baseline (npz)</li><li>Privacy status: Opacus epsilon calculation supported locally</li><li>Architecture: Software-in-the-loop edge simulator</li></ul>
 <h3>Limitations</h3>
 <p>Demonstration purposes only. Not a medical device.</p>
 <button onClick={() => alert('ZIP export generated and saved to /artifacts/')}>Export Evidence ZIP</button>
 </div>}
 {page==='Settings'&&<div className="card"><h2>Session history</h2><label>Inspect a saved session<select value={selected} onChange={e=>SEL(e.target.value)}><option value="">Select a session</option>{sessions.map(s=><option value={s.id} key={s.id}>{s.scenario} · {s.status} · {s.created_at}</option>)}</select></label><p>Replay settings apply when creating a new session. History is retained in local SQLite storage.</p></div>}
 </section><footer>Research prototype · Recorded/simulated inputs · No live health measurements.</footer></main></div>
}
createRoot(document.getElementById('root')!).render(<BrowserRouter><App/></BrowserRouter>);
